# Generated by Django 5.2.8 on 2026-08-10 11:15

import easy_thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_remove_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение'),
        ),
    ]
