# Generated by Django 5.2.8 on 2026-09-20 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='Код валюты')),
                ('nominal', models.PositiveIntegerField(default=1, verbose_name='Номинал')),
                ('rate_to_rub', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Курс к рублю')),
                ('effective_date', models.DateField(verbose_name='Дата курса')),
                ('source_url', models.URLField(blank=True, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
                'ordering': ('-effective_date', 'code'),
                'constraints': [models.UniqueConstraint(fields=('code', 'effective_date'), name='calculator_unique_currency_rate_date'), models.CheckConstraint(condition=models.Q(('rate_to_rub__gt', 0)), name='calculator_currency_rate_positive')],
            },
        ),
        migrations.CreateModel(
            name='CustomsClearanceFeeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customs_value_rub_min', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Таможенная стоимость от, ₽')),
                ('customs_value_rub_max', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Таможенная стоимость до, ₽')),
                ('fee_rub', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сбор, ₽')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('rate_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customs_clearance_fee_rates', to='calculator.rateversion', verbose_name='Версия ставок')),
            ],
            options={
                'verbose_name': 'Таможенный сбор',
                'verbose_name_plural': 'Таможенные сборы',
                'ordering': ('rate_version', 'sort_order'),
                'indexes': [models.Index(fields=['rate_version'], name='calc_customs_fee_lookup_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fee_rub__gte', 0)), name='calculator_customs_fee_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='CustomsDutyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(choices=[('up_to_3', 'Не более 3 лет'), ('3_to_5', 'Более 3, но не более 5 лет'), ('over_5', 'Более 5 лет')], max_length=12, verbose_name='Возраст автомобиля')),
                ('value_eur_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Стоимость от, евро')),
                ('value_eur_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Стоимость до, евро')),
                ('engine_capacity_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Объём двигателя от, см³')),
                ('engine_capacity_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Объём двигателя до, см³')),
                ('value_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='Процент от стоимости')),
                ('minimum_eur_per_cc', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Минимум евро за см³')),
                ('fixed_eur_per_cc', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Евро за см³')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('rate_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customs_duty_rates', to='calculator.rateversion', verbose_name='Версия ставок')),
            ],
            options={
                'verbose_name': 'Ставка таможенной пошлины',
                'verbose_name_plural': 'Ставки таможенной пошлины',
                'ordering': ('rate_version', 'age_group', 'sort_order'),
                'indexes': [models.Index(fields=['rate_version', 'age_group'], name='calc_customs_duty_lookup_idx')],
            },
        ),
    ]
