# Generated by Django 5.2.8 on 2026-09-21 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_add_customs_calculator_rates'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomsAggregateRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('powertrain', models.CharField(choices=[('combustion', 'ДВС или непоследовательный гибрид'), ('electric', 'Электромобиль или последовательный гибрид')], default='electric', max_length=20, verbose_name='Тип силовой установки')),
                ('import_duty_percentage', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Ввозная пошлина, %')),
                ('vat_percentage', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='НДС, %')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('rate_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customs_aggregate_rates', to='calculator.rateversion', verbose_name='Версия ставок')),
            ],
            options={
                'verbose_name': 'Ставка совокупного таможенного платежа',
                'verbose_name_plural': 'Ставки совокупного таможенного платежа',
                'constraints': [models.UniqueConstraint(fields=('rate_version', 'powertrain'), name='calculator_unique_aggregate_powertrain'), models.CheckConstraint(condition=models.Q(('import_duty_percentage__gte', 0)), name='calculator_aggregate_duty_nonnegative'), models.CheckConstraint(condition=models.Q(('vat_percentage__gte', 0)), name='calculator_aggregate_vat_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='ExciseRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_hp_over', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Мощность свыше, л. с.')),
                ('power_hp_up_to', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Мощность до включительно, л. с.')),
                ('rub_per_hp', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Акциз за 1 л. с., ₽')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('rate_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excise_rates', to='calculator.rateversion', verbose_name='Версия ставок')),
            ],
            options={
                'verbose_name': 'Ставка акциза',
                'verbose_name_plural': 'Ставки акциза',
                'ordering': ('rate_version', 'sort_order'),
                'constraints': [models.CheckConstraint(condition=models.Q(('rub_per_hp__gte', 0)), name='calculator_excise_nonnegative'), models.CheckConstraint(condition=models.Q(('power_hp_over__isnull', True), ('power_hp_up_to__isnull', True), ('power_hp_up_to__gt', models.F('power_hp_over')), _connector='OR'), name='calculator_excise_valid_power')],
            },
        ),
    ]
