# Generated by Django 6.0.6 on 2026-07-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SizeRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_min', models.PositiveIntegerField(verbose_name='Рост от (см)')),
                ('height_max', models.PositiveIntegerField(verbose_name='Рост до (см)')),
                ('bust_min', models.PositiveIntegerField(verbose_name='Обхват груди от (см)')),
                ('bust_max', models.PositiveIntegerField(verbose_name='Обхват груди до (см)')),
                ('waist_min', models.PositiveIntegerField(verbose_name='Талия от (см)')),
                ('waist_max', models.PositiveIntegerField(verbose_name='Талия до (см)')),
                ('hips_min', models.PositiveIntegerField(verbose_name='Бёдра от (см)')),
                ('hips_max', models.PositiveIntegerField(verbose_name='Бёдра до (см)')),
                ('size', models.CharField(max_length=10, verbose_name='Рекомендуемый размер')),
                ('description', models.TextField(blank=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Размерная рекомендация',
                'verbose_name_plural': 'Размерные рекомендации',
                'ordering': ['size'],
            },
        ),
        migrations.CreateModel(
            name='SizeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, verbose_name='Размер (RU)')),
                ('chest', models.PositiveSmallIntegerField(verbose_name='Обхват груди, см')),
                ('waist', models.PositiveSmallIntegerField(verbose_name='Обхват талии, см')),
                ('hips', models.PositiveSmallIntegerField(verbose_name='Обхват бёдер, см')),
                ('height_min', models.PositiveSmallIntegerField(verbose_name='Рост (от), см')),
                ('height_max', models.PositiveSmallIntegerField(verbose_name='Рост (до), см')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Таблица размеров',
                'ordering': ['sort_order', 'size'],
            },
        ),
    ]
