# Generated by Django 5.2.8 on 2026-08-12 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('recently_viewed', 'История просмотров'), ('home', 'Главная страница')], default='recently_viewed', max_length=50, verbose_name='Страница показа')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Чем выше число, тем ближе к началу списка.', verbose_name='Приоритет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Начало показа')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Окончание показа')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Продвигаемый товар',
                'verbose_name_plural': 'Продвигаемые товары',
                'ordering': ['-priority', '-id'],
            },
        ),
    ]
