# Generated by Django 5.2.8 on 2026-08-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_alter_promotedproduct_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotedproduct',
            name='page',
            field=models.CharField(choices=[('recently_viewed', 'История просмотров'), ('wishlist', 'Избранное'), ('home', 'Главная страница'), ('comparison', 'Сравнение')], default='recently_viewed', max_length=50, verbose_name='Страница показа'),
        ),
    ]
