# Generated by Django 5.2.8 on 2026-09-26 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_callbackrequest'),
        ('products', '0004_brand_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callbackrequest',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Обращение клиента',
                'verbose_name_plural': 'Обращения клиентов',
            },
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Город доставки'),
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callback_requests', to='products.product', verbose_name='Автомобиль'),
        ),
    ]
